import type { AttractionResponse } from '@/datamodels/attractionsmodel';
import type { HotelResponse } from '@/datamodels/hotelmodels';
import type { RestaurantResponse } from '@/datamodels/testraurantsmodel';

// Fallback static data for hotels
export const getFallbackHotels = (destinationName: string): HotelResponse[] => {
  return [
    {
      id: 'hotel-1',
      name: 'Grand Plaza Hotel',
      description: `Luxury hotel in the heart of ${destinationName} with spacious rooms and excellent amenities.`,
      address: `123 Main Street, ${destinationName}`,
      phone: '+1-555-123-4567',
      email: 'info@grandplazahotel.com',
      website: 'https://www.grandplazahotel.com',
      price: '$$$-$$$$',
      rating: '4.7',
      num_reviews: '1250',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Grand Plaza Hotel - Exterior View',
      },
      location_id: 'h001',
      latitude: '40.7128',
      longitude: '-74.006',
      web_url: 'https://www.grandplazahotel.com',
      ranking: `#1 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-2',
      name: 'Seaside Resort & Spa',
      description: `A beautiful beachfront resort in ${destinationName} offering spa services and stunning ocean views.`,
      address: `500 Beach Avenue, ${destinationName}`,
      phone: '+1-555-234-5678',
      email: 'info@seasideresort.com',
      website: 'https://www.seasideresort.com',
      price: '$$$',
      rating: '4.5',
      num_reviews: '987',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Seaside Resort & Spa - Ocean View',
      },
      location_id: 'h002',
      latitude: '40.7129',
      longitude: '-74.007',
      web_url: 'https://www.seasideresort.com',
      ranking: `#2 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-3',
      name: 'Downtown Boutique Hotel',
      description: `Charming boutique hotel in downtown ${destinationName} with uniquely designed rooms and personalized service.`,
      address: `789 Central Street, ${destinationName}`,
      phone: '+1-555-345-6789',
      email: 'info@downtownboutique.com',
      website: 'https://www.downtownboutique.com',
      price: '$$',
      rating: '4.8',
      num_reviews: '763',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Downtown Boutique Hotel - Lobby',
      },
      location_id: 'h003',
      latitude: '40.713',
      longitude: '-74.008',
      web_url: 'https://www.downtownboutique.com',
      ranking: `#3 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-4',
      name: 'Riverside Inn',
      description: `Peaceful riverside accommodation in ${destinationName} with beautiful views and a relaxing atmosphere.`,
      address: `234 River Road, ${destinationName}`,
      phone: '+1-555-456-7890',
      email: 'info@riversideinn.com',
      website: 'https://www.riversideinn.com',
      price: '$$',
      rating: '4.3',
      num_reviews: '542',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Riverside Inn - River View',
      },
      location_id: 'h004',
      latitude: '40.7131',
      longitude: '-74.009',
      web_url: 'https://www.riversideinn.com',
      ranking: `#4 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-5',
      name: 'Heritage Hotel',
      description: `Historic hotel in ${destinationName} featuring traditional architecture and modern comforts.`,
      address: `567 Heritage Avenue, ${destinationName}`,
      phone: '+1-555-567-8901',
      email: 'info@heritagehotel.com',
      website: 'https://www.heritagehotel.com',
      price: '$$$',
      rating: '4.6',
      num_reviews: '876',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Heritage Hotel - Historic Facade',
      },
      location_id: 'h005',
      latitude: '40.7132',
      longitude: '-74.01',
      web_url: 'https://www.heritagehotel.com',
      ranking: `#5 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-6',
      name: 'Business Executive Hotel',
      description: `Modern business hotel in ${destinationName} with conference facilities and executive suites.`,
      address: `890 Commerce Parkway, ${destinationName}`,
      phone: '+1-555-678-9012',
      email: 'info@businessexecutive.com',
      website: 'https://www.businessexecutive.com',
      price: '$$$',
      rating: '4.4',
      num_reviews: '654',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1555447142-1870a4fc8e0b?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1555447142-1870a4fc8e0b?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1555447142-1870a4fc8e0b?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1555447142-1870a4fc8e0b?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Business Executive Hotel - Conference Room',
      },
      location_id: 'h006',
      latitude: '40.7133',
      longitude: '-74.011',
      web_url: 'https://www.businessexecutive.com',
      ranking: `#6 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-7',
      name: 'Family Resort',
      description: `Family-friendly resort in ${destinationName} with kids' activities and spacious family rooms.`,
      address: `123 Family Circle, ${destinationName}`,
      phone: '+1-555-789-0123',
      email: 'info@familyresort.com',
      website: 'https://www.familyresort.com',
      price: '$$',
      rating: '4.5',
      num_reviews: '932',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Family Resort - Pool Area',
      },
      location_id: 'h007',
      latitude: '40.7134',
      longitude: '-74.012',
      web_url: 'https://www.familyresort.com',
      ranking: `#7 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-8',
      name: 'Alpine Lodge',
      description: `Cozy mountain lodge in ${destinationName} with rustic charm and outdoor activities.`,
      address: `456 Mountain View, ${destinationName}`,
      phone: '+1-555-890-1234',
      email: 'info@alpinelodge.com',
      website: 'https://www.alpinelodge.com',
      price: '$$',
      rating: '4.7',
      num_reviews: '587',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1521782462922-9318be1cfd04?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1521782462922-9318be1cfd04?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1521782462922-9318be1cfd04?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1521782462922-9318be1cfd04?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Alpine Lodge - Mountain View',
      },
      location_id: 'h008',
      latitude: '40.7135',
      longitude: '-74.013',
      web_url: 'https://www.alpinelodge.com',
      ranking: `#8 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-9',
      name: 'Urban Loft Hotel',
      description: `Contemporary loft-style hotel in ${destinationName} with industrial design and modern amenities.`,
      address: `789 Urban Street, ${destinationName}`,
      phone: '+1-555-901-2345',
      email: 'stay@urbanloft.com',
      website: 'https://www.urbanlofthotel.com',
      price: '$$$',
      rating: '4.6',
      num_reviews: '723',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Urban Loft Hotel - Modern Interior',
      },
      location_id: 'h009',
      latitude: '40.7136',
      longitude: '-74.014',
      web_url: 'https://www.urbanlofthotel.com',
      ranking: `#9 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
    {
      id: 'hotel-10',
      name: 'Wellness Retreat',
      description: `Holistic wellness hotel in ${destinationName} offering yoga classes, spa treatments, and healthy cuisine.`,
      address: `101 Wellness Way, ${destinationName}`,
      phone: '+1-555-012-3456',
      email: 'relax@wellnessretreat.com',
      website: 'https://www.wellnessretreat.com',
      price: '$$$$',
      rating: '4.9',
      num_reviews: '845',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Wellness Retreat - Yoga Studio',
      },
      location_id: 'h010',
      latitude: '40.7137',
      longitude: '-74.015',
      web_url: 'https://www.wellnessretreat.com',
      ranking: `#10 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
      },
    },
  ];
};

// Fallback static data for attractions
export const getFallbackAttractions = (
  destinationName: string
): AttractionResponse[] => {
  return [
    {
      name: `${destinationName} Historical Museum`,
      description: `Comprehensive museum showcasing the rich history and culture of ${destinationName} through interactive exhibits.`,
      address: `123 History Avenue, ${destinationName}`,
      address_obj: {
        street1: '123 History Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10001',
      },
      bearing: 'northwest',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d1234567-Historical_Museum-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-111-2233',
      email: 'info@historicalmuseum.com',
      website: 'https://www.historicalmuseum.com',
      fee: 'Adults $20, Children $10, Seniors $15',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7128',
      longitude: '-74.006',
      location_id: 'a001',
      location_string: destinationName,
      rating: '4.6',
      num_reviews: '1245',
      open_now_text: 'Open Now',
      parent_display_name: destinationName,
      photo: {
        id: 'p001',
        caption: 'Main Exhibition Hall',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-05-15T10:30:00-04:00',
        published_date: '2023-05-16T09:00:00-04:00',
        helpful_votes: '247',
      },
      ranking: `#1 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '1',
      raw_ranking: '4.92',
      subcategory_ranking: `#1 of 25 Museums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d1234567-Reviews-Historical_Museum-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d1234567-Historical_Museum-City_State.html',
      distance: '0.5',
      distance_string: '0.5 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Botanical Gardens`,
      description: `Beautiful botanical gardens featuring exotic plants, flowers, and themed gardens spread across acres of land.`,
      address: `456 Garden Path, ${destinationName}`,
      address_obj: {
        street1: '456 Garden Path',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10002',
      },
      bearing: 'northeast',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d2345678-Botanical_Gardens-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-222-3344',
      email: 'visit@botanicalgardens.com',
      website: 'https://www.botanicalgardens.com',
      fee: 'Adults $15, Children $7, Seniors $10',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7129',
      longitude: '-74.007',
      location_id: 'a002',
      location_string: destinationName,
      rating: '4.8',
      num_reviews: '1876',
      open_now_text: 'Open Now: 9:00 AM - 5:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p002',
        caption: 'Spring Tulip Display',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-04-10T09:15:00-04:00',
        published_date: '2023-04-11T10:00:00-04:00',
        helpful_votes: '352',
      },
      ranking: `#2 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '2',
      raw_ranking: '4.89',
      subcategory_ranking: `#1 of 15 Nature & Parks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d2345678-Reviews-Botanical_Gardens-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d2345678-Botanical_Gardens-City_State.html',
      distance: '0.8',
      distance_string: '0.8 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Art Gallery`,
      description: `Modern art gallery featuring contemporary works by local and international artists in a stunning architectural space.`,
      address: `789 Art Street, ${destinationName}`,
      address_obj: {
        street1: '789 Art Street',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10003',
      },
      bearing: 'east',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d3456789-Art_Gallery-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-333-4455',
      email: 'gallery@artgallery.com',
      website: 'https://www.artgallery.com',
      fee: 'Adults $18, Students $9, Seniors $12, Children under 12 Free',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.713',
      longitude: '-74.008',
      location_id: 'a003',
      location_string: destinationName,
      rating: '4.5',
      num_reviews: '987',
      open_now_text: 'Open Now: 10:00 AM - 6:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p003',
        caption: 'Modern Art Exhibition',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-03-25T14:20:00-04:00',
        published_date: '2023-03-26T09:30:00-04:00',
        helpful_votes: '178',
      },
      ranking: `#3 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '3',
      raw_ranking: '4.85',
      subcategory_ranking: `#2 of 25 Museums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d3456789-Reviews-Art_Gallery-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d3456789-Art_Gallery-City_State.html',
      distance: '1.2',
      distance_string: '1.2 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} National Park`,
      description: `Expansive national park offering hiking trails, wildlife viewing, and stunning natural landscapes.`,
      address: `101 Wilderness Road, ${destinationName}`,
      address_obj: {
        street1: '101 Wilderness Road',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10004',
      },
      bearing: 'south',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d4567890-National_Park-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-444-5566',
      email: 'info@nationalpark.com',
      website: 'https://www.nationalpark.com',
      fee: 'Adults $12, Children $6, Seniors $8',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7131',
      longitude: '-74.009',
      location_id: 'a004',
      location_string: destinationName,
      rating: '4.9',
      num_reviews: '2354',
      open_now_text: 'Open Now: 7:00 AM - 8:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p004',
        caption: 'Scenic Mountain View',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-06-05T08:45:00-04:00',
        published_date: '2023-06-06T09:00:00-04:00',
        helpful_votes: '423',
      },
      ranking: `#4 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '4',
      raw_ranking: '4.95',
      subcategory_ranking: `#1 of 10 National Parks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d4567890-Reviews-National_Park-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d4567890-National_Park-City_State.html',
      distance: '5.6',
      distance_string: '5.6 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Castle`,
      description: `Historic medieval castle offering guided tours, stunning architecture, and panoramic views of the city.`,
      address: `202 Castle Hill, ${destinationName}`,
      address_obj: {
        street1: '202 Castle Hill',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10005',
      },
      bearing: 'southwest',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d5678901-Castle-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-555-6677',
      email: 'tours@castle.com',
      website: 'https://www.castle.com',
      fee: 'Adults $25, Children $15, Seniors $20',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7132',
      longitude: '-74.01',
      location_id: 'a005',
      location_string: destinationName,
      rating: '4.7',
      num_reviews: '1635',
      open_now_text: 'Open Now: 9:00 AM - 7:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p005',
        caption: 'Castle Main Tower',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-02-15T11:30:00-05:00',
        published_date: '2023-02-16T09:00:00-05:00',
        helpful_votes: '287',
      },
      ranking: `#5 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '5',
      raw_ranking: '4.82',
      subcategory_ranking: `#1 of 30 Landmarks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d5678901-Reviews-Castle-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d5678901-Castle-City_State.html',
      distance: '2.3',
      distance_string: '2.3 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Science Center`,
      description: `Interactive science museum with hands-on exhibits, planetarium shows, and educational programs for all ages.`,
      address: `303 Science Boulevard, ${destinationName}`,
      address_obj: {
        street1: '303 Science Boulevard',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10006',
      },
      bearing: 'west',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d6789012-Science_Center-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-666-7788',
      email: 'info@sciencecenter.com',
      website: 'https://www.sciencecenter.com',
      fee: 'Adults $22, Children $14, Seniors $18',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7133',
      longitude: '-74.011',
      location_id: 'a006',
      location_string: destinationName,
      rating: '4.8',
      num_reviews: '1432',
      open_now_text: 'Open Now: 9:30 AM - 5:30 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p006',
        caption: 'Interactive Exhibit Hall',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-01-20T13:15:00-05:00',
        published_date: '2023-01-21T09:00:00-05:00',
        helpful_votes: '198',
      },
      ranking: `#6 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '6',
      raw_ranking: '4.79',
      subcategory_ranking: `#1 of 12 Science Museums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d6789012-Reviews-Science_Center-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d6789012-Science_Center-City_State.html',
      distance: '1.8',
      distance_string: '1.8 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Aquarium`,
      description: `World-class aquarium featuring marine life from around the globe, including interactive touch pools and daily shows.`,
      address: `404 Ocean Drive, ${destinationName}`,
      address_obj: {
        street1: '404 Ocean Drive',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10007',
      },
      bearing: 'southeast',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d7890123-Aquarium-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-777-8899',
      email: 'visit@aquarium.com',
      website: 'https://www.cityaquarium.com',
      fee: 'Adults $30, Children $20, Seniors $25',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7134',
      longitude: '-74.012',
      location_id: 'a007',
      location_string: destinationName,
      rating: '4.7',
      num_reviews: '1876',
      open_now_text: 'Open Now: 10:00 AM - 6:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p007',
        caption: 'Underwater Tunnel',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-03-05T10:45:00-05:00',
        published_date: '2023-03-06T09:00:00-05:00',
        helpful_votes: '312',
      },
      ranking: `#7 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '7',
      raw_ranking: '4.76',
      subcategory_ranking: `#1 of 5 Aquariums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d7890123-Reviews-Aquarium-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d7890123-Aquarium-City_State.html',
      distance: '2.1',
      distance_string: '2.1 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Zoo`,
      description: `Expansive zoo with over 2,000 animals from around the world in naturalistic habitats and conservation programs.`,
      address: `505 Wildlife Way, ${destinationName}`,
      address_obj: {
        street1: '505 Wildlife Way',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10008',
      },
      bearing: 'north',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d8901234-Zoo-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-888-9900',
      email: 'info@cityzoo.com',
      website: 'https://www.cityzoo.com',
      fee: 'Adults $24, Children $16, Seniors $20',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7135',
      longitude: '-74.013',
      location_id: 'a008',
      location_string: destinationName,
      rating: '4.6',
      num_reviews: '2145',
      open_now_text: 'Open Now: 9:00 AM - 5:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p008',
        caption: 'Lion Exhibit',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-04-25T11:30:00-04:00',
        published_date: '2023-04-26T09:00:00-04:00',
        helpful_votes: '276',
      },
      ranking: `#8 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '8',
      raw_ranking: '4.73',
      subcategory_ranking: `#1 of 3 Zoos in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d8901234-Reviews-Zoo-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d8901234-Zoo-City_State.html',
      distance: '3.2',
      distance_string: '3.2 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Observation Deck`,
      description: `Breathtaking 360-degree views of the city skyline from the top of the tallest building in ${destinationName}.`,
      address: `606 Skyline Avenue, ${destinationName}`,
      address_obj: {
        street1: '606 Skyline Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10009',
      },
      bearing: 'northeast',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d9012345-Observation_Deck-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-999-0011',
      email: 'tickets@observationdeck.com',
      website: 'https://www.cityobservationdeck.com',
      fee: 'Adults $32, Children $22, Seniors $28',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7136',
      longitude: '-74.014',
      location_id: 'a009',
      location_string: destinationName,
      rating: '4.9',
      num_reviews: '2876',
      open_now_text: 'Open Now: 9:00 AM - 11:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p009',
        caption: 'Sunset View from Observation Deck',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-05-30T16:45:00-04:00',
        published_date: '2023-05-31T09:00:00-04:00',
        helpful_votes: '432',
      },
      ranking: `#9 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '9',
      raw_ranking: '4.70',
      subcategory_ranking: `#1 of 8 Observation Decks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d9012345-Reviews-Observation_Deck-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d9012345-Observation_Deck-City_State.html',
      distance: '1.5',
      distance_string: '1.5 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Historic Theater`,
      description: `Beautifully restored historic theater showcasing Broadway shows, concerts, and performing arts in an elegant setting.`,
      address: `707 Broadway Avenue, ${destinationName}`,
      address_obj: {
        street1: '707 Broadway Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10010',
      },
      bearing: 'northwest',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d0123456-Historic_Theater-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-000-1122',
      email: 'tickets@historictheater.com',
      website: 'https://www.historictheater.com',
      fee: 'Varies by performance, $45-$150',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7137',
      longitude: '-74.015',
      location_id: 'a010',
      location_string: destinationName,
      rating: '4.8',
      num_reviews: '1543',
      open_now_text: 'Open for performances',
      parent_display_name: destinationName,
      photo: {
        id: 'p010',
        caption: 'Historic Theater Interior',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        uploaded_date: '2023-02-10T18:30:00-05:00',
        published_date: '2023-02-11T09:00:00-05:00',
        helpful_votes: '198',
      },
      ranking: `#10 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '10',
      raw_ranking: '4.68',
      subcategory_ranking: `#1 of 15 Theaters in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d0123456-Reviews-Historic_Theater-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d0123456-Historic_Theater-City_State.html',
      distance: '1.7',
      distance_string: '1.7 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
  ];
};

export const getFallbackRestaurants = (
  destinationName: string
): RestaurantResponse[] => {
  return [
    {
      name: 'The Golden Spoon',
      description: `Upscale fine dining restaurant in ${destinationName} offering international cuisine with a local twist.`,
      address: `123 Gourmet Avenue, ${destinationName}`,
      address_obj: {
        street1: '123 Gourmet Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northwest',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-111-2222',
      website: 'https://www.thegoldenspoon.com',
      price: '$$$$',
      price_level: '$$$$',
      rating: '4.8',
      num_reviews: '1568',
      photo: {
        id: 'r001',
        caption: 'Signature Dish - Seafood Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-05-10T19:30:00-04:00',
      },
      location_id: 'r001',
      location_string: destinationName,
      latitude: '40.7128',
      longitude: '-74.006',
      ranking: `#1 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '1',
      raw_ranking: '4.95',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d1234567-Reviews-The_Golden_Spoon-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d1234567-The_Golden_Spoon-City_State.html',
      open_now_text: 'Open Now: 5:00 PM - 11:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '0.5',
      distance_string: '0.5 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Seaside Seafood',
      description: `Fresh seafood restaurant in ${destinationName} with ocean views and locally caught fish.`,
      address: `456 Harbor Drive, ${destinationName}`,
      address_obj: {
        street1: '456 Harbor Drive',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northeast',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-222-3333',
      website: 'https://www.seasideseafood.com',
      price: '$$$',
      price_level: '$$$',
      rating: '4.6',
      num_reviews: '1246',
      photo: {
        id: 'r002',
        caption: 'Seaside Seafood Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-04-20T18:45:00-04:00',
      },
      location_id: 'r002',
      location_string: destinationName,
      latitude: '40.7129',
      longitude: '-74.007',
      ranking: `#2 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '2',
      raw_ranking: '4.92',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d2345678-Reviews-Seaside_Seafood-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d2345678-Seaside_Seafood-City_State.html',
      open_now_text: 'Open Now: 11:30 AM - 10:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '0.7',
      distance_string: '0.7 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Authentic Italian Trattoria',
      description: `Family-owned Italian restaurant in ${destinationName} serving homemade pasta and wood-fired pizza.`,
      address: `789 Pasta Lane, ${destinationName}`,
      address_obj: {
        street1: '789 Pasta Lane',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'east',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-333-4444',
      website: 'https://www.authenticitalian.com',
      price: '$$',
      price_level: '$$',
      rating: '4.7',
      num_reviews: '985',
      photo: {
        id: 'r003',
        caption: 'Homemade Pasta Special',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-03-15T19:15:00-04:00',
      },
      location_id: 'r003',
      location_string: destinationName,
      latitude: '40.713',
      longitude: '-74.008',
      ranking: `#3 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '3',
      raw_ranking: '4.88',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d3456789-Reviews-Authentic_Italian_Trattoria-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d3456789-Authentic_Italian_Trattoria-City_State.html',
      open_now_text: 'Open Now: 12:00 PM - 11:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.1',
      distance_string: '1.1 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Asian Fusion',
      description: `Modern restaurant in ${destinationName} combining flavors from different Asian cuisines in innovative dishes.`,
      address: `101 Fusion Street, ${destinationName}`,
      address_obj: {
        street1: '101 Fusion Street',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'south',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-444-5555',
      website: 'https://www.asianfusion.com',
      price: '$$$',
      price_level: '$$$',
      rating: '4.5',
      num_reviews: '872',
      photo: {
        id: 'r004',
        caption: "Chef's Special Sushi Platter",
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-06-10T20:00:00-04:00',
      },
      location_id: 'r004',
      location_string: destinationName,
      latitude: '40.7131',
      longitude: '-74.009',
      ranking: `#4 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '4',
      raw_ranking: '4.84',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d4567890-Reviews-Asian_Fusion-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d4567890-Asian_Fusion-City_State.html',
      open_now_text: 'Open Now: 5:00 PM - 11:30 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.4',
      distance_string: '1.4 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Steakhouse Prime',
      description: `Premium steakhouse in ${destinationName} serving aged beef and fine wines in an elegant setting.`,
      address: `202 Steak Boulevard, ${destinationName}`,
      address_obj: {
        street1: '202 Steak Boulevard',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'southwest',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-555-6666',
      website: 'https://www.steakhouseprime.com',
      price: '$$$$',
      price_level: '$$$$',
      rating: '4.7',
      num_reviews: '1024',
      photo: {
        id: 'r005',
        caption: 'Prime Ribeye Steak',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-05-25T19:45:00-04:00',
      },
      location_id: 'r005',
      location_string: destinationName,
      latitude: '40.7132',
      longitude: '-74.01',
      ranking: `#5 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '5',
      raw_ranking: '4.80',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d5678901-Reviews-Steakhouse_Prime-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d5678901-Steakhouse_Prime-City_State.html',
      open_now_text: 'Open Now: 5:30 PM - 11:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.9',
      distance_string: '1.9 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Farm to Table Bistro',
      description: `Sustainable restaurant in ${destinationName} using locally sourced ingredients to create seasonal dishes.`,
      address: `303 Organic Lane, ${destinationName}`,
      address_obj: {
        street1: '303 Organic Lane',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'west',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-666-7777',
      website: 'https://www.farmtotablebistro.com',
      price: '$$$',
      price_level: '$$$',
      rating: '4.8',
      num_reviews: '876',
      photo: {
        id: 'r006',
        caption: 'Seasonal Vegetable Plate',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-04-05T17:30:00-04:00',
      },
      location_id: 'r006',
      location_string: destinationName,
      latitude: '40.7133',
      longitude: '-74.011',
      ranking: `#6 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '6',
      raw_ranking: '4.78',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d6789012-Reviews-Farm_to_Table_Bistro-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d6789012-Farm_to_Table_Bistro-City_State.html',
      open_now_text: 'Open Now: 11:00 AM - 10:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.6',
      distance_string: '1.6 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Taco Fiesta',
      description: `Vibrant Mexican restaurant in ${destinationName} offering authentic tacos, margaritas, and festive atmosphere.`,
      address: `404 Salsa Street, ${destinationName}`,
      address_obj: {
        street1: '404 Salsa Street',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'southeast',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-777-8888',
      website: 'https://www.tacofiesta.com',
      price: '$$',
      price_level: '$$',
      rating: '4.6',
      num_reviews: '932',
      photo: {
        id: 'r007',
        caption: 'Authentic Street Tacos',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-03-20T18:15:00-04:00',
      },
      location_id: 'r007',
      location_string: destinationName,
      latitude: '40.7134',
      longitude: '-74.012',
      ranking: `#7 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '7',
      raw_ranking: '4.75',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d7890123-Reviews-Taco_Fiesta-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d7890123-Taco_Fiesta-City_State.html',
      open_now_text: 'Open Now: 11:00 AM - 11:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.3',
      distance_string: '1.3 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Sushi Paradise',
      description: `Upscale Japanese restaurant in ${destinationName} specializing in fresh sushi, sashimi, and traditional dishes.`,
      address: `505 Wasabi Way, ${destinationName}`,
      address_obj: {
        street1: '505 Wasabi Way',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'north',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-888-9999',
      website: 'https://www.sushiparadise.com',
      price: '$$$',
      price_level: '$$$',
      rating: '4.9',
      num_reviews: '1087',
      photo: {
        id: 'r008',
        caption: 'Omakase Sushi Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-06-15T19:00:00-04:00',
      },
      location_id: 'r008',
      location_string: destinationName,
      latitude: '40.7135',
      longitude: '-74.013',
      ranking: `#8 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '8',
      raw_ranking: '4.72',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d8901234-Reviews-Sushi_Paradise-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d8901234-Sushi_Paradise-City_State.html',
      open_now_text: 'Open Now: 12:00 PM - 10:30 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.7',
      distance_string: '1.7 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Café Parisienne',
      description: `Charming French café in ${destinationName} serving pastries, coffee, and classic bistro fare in a cozy atmosphere.`,
      address: `606 Croissant Boulevard, ${destinationName}`,
      address_obj: {
        street1: '606 Croissant Boulevard',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northeast',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-999-0000',
      website: 'https://www.cafeparisienne.com',
      price: '$$',
      price_level: '$$',
      rating: '4.5',
      num_reviews: '845',
      photo: {
        id: 'r009',
        caption: 'French Pastry Selection',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-02-25T09:30:00-05:00',
      },
      location_id: 'r009',
      location_string: destinationName,
      latitude: '40.7136',
      longitude: '-74.014',
      ranking: `#9 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '9',
      raw_ranking: '4.70',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d9012345-Reviews-Cafe_Parisienne-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d9012345-Cafe_Parisienne-City_State.html',
      open_now_text: 'Open Now: 7:00 AM - 9:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.2',
      distance_string: '1.2 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Smokehouse BBQ',
      description: `Authentic barbecue restaurant in ${destinationName} with slow-smoked meats, homemade sauces, and hearty sides.`,
      address: `707 Brisket Road, ${destinationName}`,
      address_obj: {
        street1: '707 Brisket Road',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northwest',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-000-1111',
      website: 'https://www.smokehousebbq.com',
      price: '$$',
      price_level: '$$',
      rating: '4.7',
      num_reviews: '967',
      photo: {
        id: 'r010',
        caption: 'Smoked Brisket Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },

        uploaded_date: '2023-05-05T16:45:00-04:00',
      },
      location_id: 'r010',
      location_string: destinationName,
      latitude: '40.7137',
      longitude: '-74.015',
      ranking: `#10 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '10',
      raw_ranking: '4.68',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d0123456-Reviews-Smokehouse_BBQ-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d0123456-Smokehouse_BBQ-City_State.html',
      open_now_text: 'Open Now: 11:30 AM - 10:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '1.8',
      distance_string: '1.8 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
  ];
};
