import type { AttractionResponse } from '@/datamodels/attractionsmodel';
import type { HotelResponse } from '@/datamodels/hotelmodels';
import type { RestaurantResponse } from '@/datamodels/testraurantsmodel';

// Fallback static data for hotels
export const getFallbackHotels = (destinationName: string): HotelResponse[] => {
  return [
    {
      id: 'hotel-1',
      name: 'Grand Plaza Hotel',
      description: `Luxury hotel in the heart of ${destinationName} with spacious rooms and excellent amenities.`,
      address: `123 Main Street, ${destinationName}`,
      phone: '+1-555-123-4567',
      email: 'info@grandplazahotel.com',
      website: 'https://www.grandplazahotel.com',
      price: '$$$-$$$$',
      rating: '4.7',
      num_reviews: '1250',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Grand Plaza Hotel - Exterior View',
      },
      location_id: 'h001',
      latitude: '40.7128',
      longitude: '-74.006',
      web_url: 'https://www.grandplazahotel.com',
      ranking: `#1 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
        week_ranges: [
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
        ],
      },
    },
    {
      id: 'hotel-2',
      name: 'Seaside Resort & Spa',
      description: `A beautiful beachfront resort in ${destinationName} offering spa services and stunning ocean views.`,
      address: `500 Beach Avenue, ${destinationName}`,
      phone: '+1-555-234-5678',
      email: 'info@seasideresort.com',
      website: 'https://www.seasideresort.com',
      price: '$$$',
      rating: '4.5',
      num_reviews: '987',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Seaside Resort & Spa - Ocean View',
      },
      location_id: 'h002',
      latitude: '40.7129',
      longitude: '-74.007',
      web_url: 'https://www.seasideresort.com',
      ranking: `#2 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
        week_ranges: [
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
        ],
      },
    },
    {
      id: 'hotel-3',
      name: 'Downtown Boutique Hotel',
      description: `Charming boutique hotel in downtown ${destinationName} with uniquely designed rooms and personalized service.`,
      address: `789 Central Street, ${destinationName}`,
      phone: '+1-555-345-6789',
      email: 'info@downtownboutique.com',
      website: 'https://www.downtownboutique.com',
      price: '$$',
      rating: '4.8',
      num_reviews: '763',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Downtown Boutique Hotel - Lobby',
      },
      location_id: 'h003',
      latitude: '40.713',
      longitude: '-74.008',
      web_url: 'https://www.downtownboutique.com',
      ranking: `#3 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
        week_ranges: [
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
        ],
      },
    },
    {
      id: 'hotel-4',
      name: 'Riverside Inn',
      description: `Peaceful riverside accommodation in ${destinationName} with beautiful views and a relaxing atmosphere.`,
      address: `234 River Road, ${destinationName}`,
      phone: '+1-555-456-7890',
      email: 'info@riversideinn.com',
      website: 'https://www.riversideinn.com',
      price: '$$',
      rating: '4.3',
      num_reviews: '542',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Riverside Inn - River View',
      },
      location_id: 'h004',
      latitude: '40.7131',
      longitude: '-74.009',
      web_url: 'https://www.riversideinn.com',
      ranking: `#4 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
        week_ranges: [
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
        ],
      },
    },
    {
      id: 'hotel-5',
      name: 'Heritage Hotel',
      description: `Historic hotel in ${destinationName} featuring traditional architecture and modern comforts.`,
      address: `567 Heritage Avenue, ${destinationName}`,
      phone: '+1-555-567-8901',
      email: 'info@heritagehotel.com',
      website: 'https://www.heritagehotel.com',
      price: '$$$',
      rating: '4.6',
      num_reviews: '876',
      photo: {
        images: {
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        caption: 'Heritage Hotel - Historic Facade',
      },
      location_id: 'h005',
      latitude: '40.7132',
      longitude: '-74.01',
      web_url: 'https://www.heritagehotel.com',
      ranking: `#5 of 500 hotels in ${destinationName}`,
      category: { key: 'hotel', name: 'Hotel' },
      open_now_text: 'Open Now',
      hours: {
        timezone: 'America/New_York',
        week_ranges: [
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
          [{ open_time: 0, close_time: 1439 }],
        ],
      },
    },
  ];
};

// Fallback static data for attractions
export const getFallbackAttractions = (
  destinationName: string
): AttractionResponse[] => {
  return [
    {
      name: `${destinationName} Historical Museum`,
      description: `Comprehensive museum showcasing the rich history and culture of ${destinationName} through interactive exhibits.`,
      address: `123 History Avenue, ${destinationName}`,
      address_obj: {
        street1: '123 History Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10001',
      },
      bearing: 'northwest',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d1234567-Historical_Museum-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-111-2233',
      email: 'info@historicalmuseum.com',
      website: 'https://www.historicalmuseum.com',
      fee: 'Adults $20, Children $10, Seniors $15',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7128',
      longitude: '-74.006',
      location_id: 'a001',
      location_string: destinationName,
      rating: '4.6',
      num_reviews: '1245',
      open_now_text: 'Open Now',
      parent_display_name: destinationName,
      photo: {
        id: 'p001',
        caption: 'Main Exhibition Hall',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-05-15T10:30:00-04:00',
        published_date: '2023-05-16T09:00:00-04:00',
        helpful_votes: '247',
      },
      ranking: `#1 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '1',
      raw_ranking: '4.92',
      subcategory_ranking: `#1 of 25 Museums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d1234567-Reviews-Historical_Museum-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d1234567-Historical_Museum-City_State.html',
      distance: '0.5',
      distance_string: '0.5 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Botanical Gardens`,
      description: `Beautiful botanical gardens featuring exotic plants, flowers, and themed gardens spread across acres of land.`,
      address: `456 Garden Path, ${destinationName}`,
      address_obj: {
        street1: '456 Garden Path',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10002',
      },
      bearing: 'northeast',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d2345678-Botanical_Gardens-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-222-3344',
      email: 'visit@botanicalgardens.com',
      website: 'https://www.botanicalgardens.com',
      fee: 'Adults $15, Children $7, Seniors $10',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7129',
      longitude: '-74.007',
      location_id: 'a002',
      location_string: destinationName,
      rating: '4.8',
      num_reviews: '1876',
      open_now_text: 'Open Now: 9:00 AM - 5:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p002',
        caption: 'Spring Tulip Display',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-04-10T09:15:00-04:00',
        published_date: '2023-04-11T10:00:00-04:00',
        helpful_votes: '352',
      },
      ranking: `#2 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '2',
      raw_ranking: '4.89',
      subcategory_ranking: `#1 of 15 Nature & Parks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d2345678-Reviews-Botanical_Gardens-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d2345678-Botanical_Gardens-City_State.html',
      distance: '0.8',
      distance_string: '0.8 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Art Gallery`,
      description: `Modern art gallery featuring contemporary works by local and international artists in a stunning architectural space.`,
      address: `789 Art Street, ${destinationName}`,
      address_obj: {
        street1: '789 Art Street',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10003',
      },
      bearing: 'east',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d3456789-Art_Gallery-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-333-4455',
      email: 'gallery@artgallery.com',
      website: 'https://www.artgallery.com',
      fee: 'Adults $18, Students $9, Seniors $12, Children under 12 Free',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.713',
      longitude: '-74.008',
      location_id: 'a003',
      location_string: destinationName,
      rating: '4.5',
      num_reviews: '987',
      open_now_text: 'Open Now: 10:00 AM - 6:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p003',
        caption: 'Modern Art Exhibition',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-03-25T14:20:00-04:00',
        published_date: '2023-03-26T09:30:00-04:00',
        helpful_votes: '178',
      },
      ranking: `#3 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '3',
      raw_ranking: '4.85',
      subcategory_ranking: `#2 of 25 Museums in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d3456789-Reviews-Art_Gallery-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d3456789-Art_Gallery-City_State.html',
      distance: '1.2',
      distance_string: '1.2 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} National Park`,
      description: `Expansive national park offering hiking trails, wildlife viewing, and stunning natural landscapes.`,
      address: `101 Wilderness Road, ${destinationName}`,
      address_obj: {
        street1: '101 Wilderness Road',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10004',
      },
      bearing: 'south',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d4567890-National_Park-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-444-5566',
      email: 'info@nationalpark.com',
      website: 'https://www.nationalpark.com',
      fee: 'Adults $12, Children $6, Seniors $8',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7131',
      longitude: '-74.009',
      location_id: 'a004',
      location_string: destinationName,
      rating: '4.9',
      num_reviews: '2354',
      open_now_text: 'Open Now: 7:00 AM - 8:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p004',
        caption: 'Scenic Mountain View',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-06-05T08:45:00-04:00',
        published_date: '2023-06-06T09:00:00-04:00',
        helpful_votes: '423',
      },
      ranking: `#4 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '4',
      raw_ranking: '4.95',
      subcategory_ranking: `#1 of 10 National Parks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d4567890-Reviews-National_Park-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d4567890-National_Park-City_State.html',
      distance: '5.6',
      distance_string: '5.6 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: `${destinationName} Castle`,
      description: `Historic medieval castle offering guided tours, stunning architecture, and panoramic views of the city.`,
      address: `202 Castle Hill, ${destinationName}`,
      address_obj: {
        street1: '202 Castle Hill',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
        postalcode: '10005',
      },
      bearing: 'southwest',
      booking: {
        provider: 'TripAdvisor',
        url: 'https://www.tripadvisor.com/Attraction_Booking-g123456-d5678901-Castle-City_State.html',
      },
      category: { key: 'attraction', name: 'Attraction' },
      phone: '+1-555-555-6677',
      email: 'tours@castle.com',
      website: 'https://www.castle.com',
      fee: 'Adults $25, Children $15, Seniors $20',
      is_closed: false,
      is_long_closed: false,
      latitude: '40.7132',
      longitude: '-74.01',
      location_id: 'a005',
      location_string: destinationName,
      rating: '4.7',
      num_reviews: '1635',
      open_now_text: 'Open Now: 9:00 AM - 7:00 PM',
      parent_display_name: destinationName,
      photo: {
        id: 'p005',
        caption: 'Castle Main Tower',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-02-15T11:30:00-05:00',
        published_date: '2023-02-16T09:00:00-05:00',
        helpful_votes: '287',
      },
      ranking: `#5 of 200 attractions in ${destinationName}`,
      ranking_category: 'attraction',
      ranking_denominator: '200',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '5',
      raw_ranking: '4.82',
      subcategory_ranking: `#1 of 30 Landmarks in ${destinationName}`,
      timezone: 'America/New_York',
      web_url:
        'https://www.tripadvisor.com/Attraction_Review-g123456-d5678901-Reviews-Castle-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d5678901-Castle-City_State.html',
      distance: '2.3',
      distance_string: '2.3 mi',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
  ];
};

// Fallback static data for restaurants
export const getFallbackRestaurants = (
  destinationName: string
): RestaurantResponse[] => {
  return [
    {
      name: 'The Golden Spoon',
      description: `Upscale fine dining restaurant in ${destinationName} offering international cuisine with a local twist.`,
      address: `123 Gourmet Avenue, ${destinationName}`,
      address_obj: {
        street1: '123 Gourmet Avenue',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northwest',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-111-2222',
      website: 'https://www.thegoldenspoon.com',
      price: '$$$$',
      price_level: '$$$$',
      rating: '4.8',
      num_reviews: '1568',
      photo: {
        id: 'r001',
        caption: 'Signature Dish - Seafood Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-05-10T19:30:00-04:00',
      },
      location_id: 'r001',
      location_string: destinationName,
      latitude: '40.7128',
      longitude: '-74.006',
      ranking: `#1 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '1',
      raw_ranking: '4.95',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d1234567-Reviews-The_Golden_Spoon-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d1234567-The_Golden_Spoon-City_State.html',
      open_now_text: 'Open Now: 5:00 PM - 11:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '0.5',
      distance_string: '0.5 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
    {
      name: 'Seaside Seafood',
      description: `Fresh seafood restaurant in ${destinationName} with ocean views and locally caught fish.`,
      address: `456 Harbor Drive, ${destinationName}`,
      address_obj: {
        street1: '456 Harbor Drive',
        street2: '',
        city: destinationName,
        state: 'NY',
        country: 'United States',
      },
      bearing: 'northeast',
      category: { key: 'restaurant', name: 'Restaurant' },
      phone: '+1-555-222-3333',
      website: 'https://www.seasideseafood.com',
      price: '$$$',
      price_level: '$$$',
      rating: '4.6',
      num_reviews: '1246',
      photo: {
        id: 'r002',
        caption: 'Seaside Seafood Platter',
        images: {
          small: {
            width: '350',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=350&auto=format&fit=crop',
            height: '233',
          },
          medium: {
            width: '500',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=500&auto=format&fit=crop',
            height: '333',
          },
          large: {
            width: '1080',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=1080&auto=format&fit=crop',
            height: '720',
          },
          original: {
            width: '1600',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=1600&auto=format&fit=crop',
            height: '1067',
          },
          thumbnail: {
            width: '150',
            url: 'https://images.unsplash.com/photo-1560611588-163f49a6cbe5?q=80&w=150&auto=format&fit=crop',
            height: '100',
          },
        },
        is_blessed: true,
        uploaded_date: '2023-04-20T18:45:00-04:00',
      },
      location_id: 'r002',
      location_string: destinationName,
      latitude: '40.7129',
      longitude: '-74.007',
      ranking: `#2 of 1000 restaurants in ${destinationName}`,
      ranking_category: 'restaurant',
      ranking_denominator: '1000',
      ranking_geo: destinationName,
      ranking_geo_id: 'd001',
      ranking_position: '2',
      raw_ranking: '4.92',
      web_url:
        'https://www.tripadvisor.com/Restaurant_Review-g123456-d2345678-Reviews-Seaside_Seafood-City_State.html',
      write_review:
        'https://www.tripadvisor.com/UserReview-g123456-d2345678-Seaside_Seafood-City_State.html',
      open_now_text: 'Open Now: 11:30 AM - 10:00 PM',
      is_closed: false,
      is_long_closed: false,
      distance: '0.7',
      distance_string: '0.7 mi',
      is_candidate_for_contact_info_suppression: false,
      timezone: 'America/New_York',
      preferred_map_engine: 'default',
      doubleclick_zone: 'na.us.ny.new_york_city',
    },
  ];
};
